### PR TITLE
Sort, Search and Filter functionality

### PR DESCRIPTION
**Pull request by TheMimStack**
Co-authored-by: Braddon Murphy <BraddonLee@users.noreply.github.com>

### CODE REVIEW

**Review by tommmyngo — APPROVED** [review]
looks good!

**Comment by BraddonLee** [comment]
I approve of these changes, co-authored by yours truly

**Review by camoy1 — APPROVED** [review]
Looks good! Recommend making sorting functionality into separate files so variables can be globally used.

**Review by moore76sc — APPROVED** [review]
Please add pseudocode when you get a chance to detail functions.

**Pull request merged**
