### PR TITLE
Virtual List functional

### PR DESCRIPTION
**Pull request by tommmyngo**
Updated with last week's changes including:
Updating component to standby for SSR loading
Changing cells to have white bg and black font as default
Updating package,json for package version control and paths
Virtual List implementation in its basic form

### CODE REVIEW

**Review by moore76sc — APPROVED** [review]
Looks good.

**Review by camoy1 — APPROVED** [review]
looks good; for future PRs, need to go back to add descriptive info for code

**Review by TheMimStack — APPROVED** [review]
Looks good.

**Comment by BraddonLee** [comment]
Great stuff, Tommy!

**Pull request merged**
