### PR TITLE
filterBy is now function and accounts for filtering of multiple columns

### PR DESCRIPTION
**Pull request by moore76sc**

### CODE REVIEW

**Review by TheMimStack — COMMENTED** [review]
Thanks for refactoring, Adam!
Could we consider separating the icons from the sort function before merging this and
also adding comments to the filterBy function?
Especially since the functionality is not at 100%, it might make debugging the code easier for everyone? 

I'll review in more detail tomorrow. Thanks again for the PR.

**Comment by BraddonLee** [comment]
Fine work, Adam

**Review by tommmyngo — APPROVED** [review]
This looks great, very concise. Thanks Adam

**Review by TheMimStack — APPROVED** [review]
Great job!

**Review by BraddonLee — APPROVED** [review]
Merge!

**Review by camoy1 — APPROVED** [review]
Thanks for refactoring! Glad that you got it to work. Tommy and I will take on refactoring the sort arrow.

**Pull request merged**
